site_name: THM Writeups | Vasanth Vanan
repo_url: https://github.com/VasanthVanan/tryhackme-writeups
theme:
  font:
    text: Roboto
  name: material
  primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  icon:
    repo: fontawesome/brands/github 
nav:
  - Easy Challenges:
    - ColddBox Easy: easy/colddbox.md
    - ARcHanG3l: easy/ARcHanG3l.md
    - ToolsRUs: easy/ToolsRUs.md
    - Wordpress CVE: easy/CVE-2021-29447.md
  - Medium Challenges:
    - medium/index.md
  - Hard Challenges:
    - hard/index.md
  - Insane Challenges:
    - insane/index.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - def_list
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
